# Generated by Django 5.1.4 on 2026-04-10 16:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=500)),
                ("price_per_hour", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "surface_type",
                    models.CharField(
                        choices=[
                            ("grass", "Grass"),
                            ("artificial", "Artificial"),
                            ("futsal", "Futsal"),
                        ],
                        default="grass",
                        max_length=20,
                    ),
                ),
                ("amenities", models.JSONField(blank=True, default=list)),
                (
                    "size",
                    models.CharField(
                        choices=[("5v5", "5v5"), ("7v7", "7v7"), ("11v11", "11v11")],
                        default="5v5",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "pitch",
                "verbose_name_plural": "pitches",
                "ordering": ["-created_at"],
            },
        ),
    ]
