# Generated by Django 5.1.4 on 2026-04-10 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pitches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pitch",
            index=models.Index(
                fields=["is_active", "-created_at"], name="pitches_pit_is_acti_4d2d71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pitch",
            index=models.Index(
                fields=["surface_type", "is_active"], name="pitches_pit_surface_a58604_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pitch",
            index=models.Index(fields=["size", "is_active"], name="pitches_pit_size_313276_idx"),
        ),
    ]
