"""
Fixture generation service for three tournament formats.

Algorithm designs from Opus 4.6:
  - Round-robin: circle method (N*(N-1)/2 fixtures, handles odd N with BYE sentinel)
  - Knockout: single-elimination with byes (next power-of-2 bracket)
  - Group knockout: snake-distributed groups → circle RR within each → KO seeding

Standing is NOT stored — computed dynamically by standings.py.
Knockout round N+1 is auto-generated by knockout.py on round N completion.
"""

from __future__ import annotations

import datetime

from django.db import transaction

from apps.tournaments.models import (
    Fixture,
    FixtureStage,
    FixtureStatus,
    Tournament,
    TournamentFormat,
    TournamentTeam,
)

_BYE = None  # sentinel for circle-method odd-N padding
_GROUP_NAMES = ["A", "B", "C", "D"]
_VALID_GROUP_KO_SIZES = {8, 10, 12, 16, 20, 24, 28, 32}


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def generate_fixtures(tournament: Tournament) -> list[Fixture]:
    """Generate all fixtures for a tournament and persist them.

    Called once when the owner closes registration.
    Returns the list of created Fixture objects.
    """
    teams = list(TournamentTeam.objects.filter(tournament=tournament).order_by("registered_at"))
    if len(teams) < 2:
        raise ValueError("Need at least 2 teams to generate fixtures.")

    format_ = tournament.format
    if format_ == TournamentFormat.ROUND_ROBIN:
        fixtures = _generate_round_robin(tournament, teams)
    elif format_ == TournamentFormat.KNOCKOUT:
        fixtures = _generate_knockout_round1(tournament, teams)
    elif format_ == TournamentFormat.GROUP_KNOCKOUT:
        fixtures = _generate_group_knockout(tournament, teams)
    else:
        raise ValueError(f"Unknown tournament format: {format_}")

    return fixtures


def validate_team_count(tournament: Tournament) -> None:
    """Raise ValueError if registered team count is invalid for the format."""
    n = TournamentTeam.objects.filter(tournament=tournament).count()
    if n < 2:
        raise ValueError(f"Need at least 2 teams; got {n}.")
    if tournament.format == TournamentFormat.GROUP_KNOCKOUT and n not in _VALID_GROUP_KO_SIZES:
        raise ValueError(
            f"Group-knockout requires a team count in {sorted(_VALID_GROUP_KO_SIZES)}; got {n}."
        )


# ---------------------------------------------------------------------------
# Round-robin — circle method
# ---------------------------------------------------------------------------


def _generate_round_robin(
    tournament: Tournament,
    teams: list[TournamentTeam],
) -> list[Fixture]:
    """Standard circle-method round-robin.

    Produces N*(N-1)/2 unique fixtures for N teams.
    Odd N: pad with a BYE sentinel (None) so every team gets a rest round.
    """
    n = len(teams)
    indices: list[int | None] = list(range(n))
    if n % 2 == 1:
        indices.append(None)  # BYE sentinel

    num_slots = len(indices)
    num_rounds = num_slots - 1
    half = num_slots // 2

    pairs: list[tuple[TournamentTeam | None, TournamentTeam | None]] = []
    arr = indices[:]

    for r in range(num_rounds):
        for i in range(half):
            j = num_slots - 1 - i
            a_idx = arr[i]
            b_idx = arr[j]
            if a_idx is None or b_idx is None:
                continue  # skip BYE pair
            a = teams[a_idx]
            b = teams[b_idx]
            # Alternate home/away across rounds to balance
            if (r + i) % 2 == 0:
                pairs.append((a, b))
            else:
                pairs.append((b, a))

        # Rotate: keep arr[0] fixed, rotate arr[1:] right by 1
        arr = [arr[0]] + [arr[-1]] + arr[1:-1]

    start_dt = datetime.datetime.combine(
        tournament.start_date, datetime.time(18, 0), tzinfo=datetime.UTC
    )
    fixtures_to_create = []
    for round_num, (home, away) in enumerate(pairs, start=1):
        scheduled = start_dt + datetime.timedelta(days=(round_num - 1) // max(half - 1, 1))
        fixtures_to_create.append(
            Fixture(
                tournament=tournament,
                home_team=home,
                away_team=away,
                round_number=round_num,
                scheduled_at=scheduled,
                status=FixtureStatus.SCHEDULED,
                stage=FixtureStage.KNOCKOUT,
                is_bye=False,
            )
        )

    with transaction.atomic():
        created = Fixture.objects.bulk_create(fixtures_to_create)
    return created


# ---------------------------------------------------------------------------
# Knockout — single elimination with byes
# ---------------------------------------------------------------------------


def _next_power_of_2(n: int) -> int:
    if n <= 1:
        return 1
    return 1 << (n - 1).bit_length()


def _generate_knockout_round1(
    tournament: Tournament,
    teams: list[TournamentTeam],
    stage: str = FixtureStage.KNOCKOUT,
    group_name: str = "",
    round_offset: int = 0,
) -> list[Fixture]:
    """Generate round-1 knockout fixtures.

    Teams are seeded in registration order (index 0 = top seed).
    Byes are awarded to the top seeds when N is not a power of 2.

    Returns list of created Fixture objects.
    """
    n = len(teams)
    bracket_size = _next_power_of_2(n)
    num_byes = bracket_size - n

    bye_seeds = teams[:num_byes]
    playing = teams[num_byes:]

    start_dt = datetime.datetime.combine(
        tournament.start_date, datetime.time(18, 0), tzinfo=datetime.UTC
    )
    round_number = 1 + round_offset

    fixtures_to_create: list[Fixture] = []

    # Bye fixtures — pre-completed so they don't block round-completion checks
    for seed in bye_seeds:
        fixtures_to_create.append(
            Fixture(
                tournament=tournament,
                home_team=seed,
                away_team=None,
                round_number=round_number,
                scheduled_at=None,
                home_score=None,
                away_score=None,
                status=FixtureStatus.COMPLETED,
                stage=stage,
                group_name=group_name,
                is_bye=True,
            )
        )

    # Real matches — pair highest seed vs lowest seed inward
    lo, hi = 0, len(playing) - 1
    while lo < hi:
        fixtures_to_create.append(
            Fixture(
                tournament=tournament,
                home_team=playing[lo],
                away_team=playing[hi],
                round_number=round_number,
                scheduled_at=start_dt,
                status=FixtureStatus.SCHEDULED,
                stage=stage,
                group_name=group_name,
                is_bye=False,
            )
        )
        lo += 1
        hi -= 1

    with transaction.atomic():
        created = Fixture.objects.bulk_create(fixtures_to_create)
    return created


# ---------------------------------------------------------------------------
# Group then knockout
# ---------------------------------------------------------------------------


def _generate_group_knockout(
    tournament: Tournament,
    teams: list[TournamentTeam],
) -> list[Fixture]:
    """Generate group-stage fixtures using snake distribution.

    Supported team counts: {8, 10, 12, 16, 20, 24, 28, 32}
    Groups: 2 groups for N≤12, else 4 groups.
    After the group stage completes, knockout fixtures are auto-generated
    by knockout.py when standings are resolved.
    """
    n = len(teams)
    if n not in _VALID_GROUP_KO_SIZES:
        raise ValueError(
            f"Group-knockout requires team count in {sorted(_VALID_GROUP_KO_SIZES)}; got {n}."
        )

    num_groups = 2 if n <= 12 else 4

    # Snake distribution: team[i] → groups[i % num_groups]
    groups: list[list[TournamentTeam]] = [[] for _ in range(num_groups)]
    for i, team in enumerate(teams):
        groups[i % num_groups].append(team)

    all_fixtures: list[Fixture] = []
    for g_idx, group_teams in enumerate(groups):
        group_name = _GROUP_NAMES[g_idx]
        fixtures = _generate_round_robin_group(tournament, group_teams, group_name)
        all_fixtures.extend(fixtures)

    return all_fixtures


def _generate_round_robin_group(
    tournament: Tournament,
    teams: list[TournamentTeam],
    group_name: str,
) -> list[Fixture]:
    """Circle-method RR for a single group. Stage = group."""
    n = len(teams)
    indices: list[int | None] = list(range(n))
    if n % 2 == 1:
        indices.append(None)

    num_slots = len(indices)
    num_rounds = num_slots - 1
    half = num_slots // 2

    pairs: list[tuple[TournamentTeam, TournamentTeam]] = []
    arr = indices[:]

    for r in range(num_rounds):
        for i in range(half):
            j = num_slots - 1 - i
            a_idx = arr[i]
            b_idx = arr[j]
            if a_idx is None or b_idx is None:
                continue
            a = teams[a_idx]
            b = teams[b_idx]
            if (r + i) % 2 == 0:
                pairs.append((a, b))
            else:
                pairs.append((b, a))
        arr = [arr[0]] + [arr[-1]] + arr[1:-1]

    start_dt = datetime.datetime.combine(
        tournament.start_date, datetime.time(18, 0), tzinfo=datetime.UTC
    )
    fixtures_to_create = []
    for round_num, (home, away) in enumerate(pairs, start=1):
        scheduled = start_dt + datetime.timedelta(days=(round_num - 1) // max(half - 1, 1))
        fixtures_to_create.append(
            Fixture(
                tournament=tournament,
                home_team=home,
                away_team=away,
                round_number=round_num,
                scheduled_at=scheduled,
                status=FixtureStatus.SCHEDULED,
                stage=FixtureStage.GROUP,
                group_name=group_name,
                is_bye=False,
            )
        )

    with transaction.atomic():
        created = Fixture.objects.bulk_create(fixtures_to_create)
    return created
