# Generated by Django 5.1.4 on 2026-04-10 11:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('sport_type', models.CharField(choices=[('5v5', '5 vs 5'), ('7v7', '7 vs 7')], max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('address_ar', models.CharField(max_length=500)),
                ('address_en', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('price_per_slot', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='draft', max_length=20)),
                ('rejection_note', models.TextField(blank=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='stadiums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stadium',
                'verbose_name_plural': 'stadiums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StadiumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='stadiums/photos/original/')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('medium_url', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_cover', models.BooleanField(db_index=True, default=False)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stadiums.stadium')),
            ],
            options={
                'verbose_name': 'stadium photo',
                'verbose_name_plural': 'stadium photos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], db_index=True, default='available', max_length=20)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='stadiums.stadium')),
            ],
            options={
                'verbose_name': 'slot',
                'verbose_name_plural': 'slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('stadium', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='OperatingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='stadiums.stadium')),
            ],
            options={
                'verbose_name': 'operating hour',
                'verbose_name_plural': 'operating hours',
                'ordering': ['day_of_week'],
                'unique_together': {('stadium', 'day_of_week')},
            },
        ),
    ]
