# Generated by Django 5.1.4 on 2026-04-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stadiums", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stadiumphoto",
            name="medium_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="stadiumphoto",
            name="thumbnail_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
