# Generated by Django 5.2.13 on 2026-04-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stadiums", "0002_increase_photo_url_max_length"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="slot",
            index=models.Index(fields=["date", "end_time"], name="slot_date_end_time_idx"),
        ),
    ]
