# Generated by Django 5.2.13 on 2026-04-12 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
        ("stadiums", "0003_add_booking_and_slot_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["player", "-created_at"], name="booking_player_createdat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["stadium", "-created_at"], name="booking_stadium_createdat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status", "slot"], name="booking_status_slot_idx"),
        ),
    ]
